---
title: "R Notebook"
output: html_notebook
---


Call library and set API key
```{r}
library(DatawRappr)
library(tidyverse)
#datawrapper_auth(api_key =  "sOa38CEKU6BxzY7v2OS7KwL3PN2ZZO9qNmjIty4hqa82LZMJgnW7D90Wx9uHPIqA")

```



######## CREATE BASIC BAR CHART FROM TEMPLATE ############
Template: https://datawrapper.dwcdn.net/iQa5S/1/ 

call in your bar chart data 
(call in test.csv to test)
```{r}
new_data <- read.csv("INSERT-CSV.csv")
head(new_data)

```


Duplicate the chart template, edit and publish
```{r}
#duplicate the original bar chart template
# https://app.datawrapper.de/chart/Ai2xB/visualize#refine
new_chart <- dw_copy_chart(copy_from = "iQa5S")

#Add new data to chart
dw_data_to_chart(new_data, new_chart)

#Edit headline, chatter, source, byline
dw_edit_chart(new_chart, 
              title = "INSERT HED", 
              intro = "INSERT CHATTER",
              source_name = "INSERT SOURCE",
              byline = "INSERT BYLINE"
              )


#publish
dw_publish_chart(new_chart)

```



######## CREATE BASIC POLL BAR CHART FROM TEMPLATE ############
Template: https://datawrapper.dwcdn.net/z2NGm/1/

Call in new poll data
(call in test2.csv to test)
```{r}
new_poll_data <- read.csv("INSERT-CSV.csv")
head(new_poll_data)
```



Duplicate the chart template, edit and publish
```{r}
#duplicate the original bar chart template
# https://app.datawrapper.de/chart/Ai2xB/visualize#refine
new_poll_chart <- dw_copy_chart(copy_from = "z2NGm")

#Add new data to chart
dw_data_to_chart(new_poll_data, new_poll_chart)

#Edit headline, chatter, source, byline
dw_edit_chart(new_poll_chart, 
              title = "INSERT HED", 
              intro = "INSERT CHATTER",
              source_name = "INSERT SOURCE",
              byline = "INSERT BYLINE")


#publish
dw_publish_chart(new_poll_chart)

```